CREATE TABLE IF NOT EXISTS luma_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  external_id VARCHAR(128) NOT NULL,
  title VARCHAR(500) NOT NULL DEFAULT '',
  start_at DATETIME(3) NULL,
  end_at DATETIME(3) NULL,
  timezone VARCHAR(64) NULL,
  url VARCHAR(500) NULL,
  cover_url VARCHAR(500) NULL,
  location_json JSON NULL,
  meeting_url VARCHAR(500) NULL,
  status VARCHAR(64) NULL,
  payload_json JSON NOT NULL,
  synced_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uniq_luma_user_event (user_id, external_id),
  INDEX idx_luma_user_start (user_id, start_at),
  CONSTRAINT fk_luma_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS eventbrite_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  external_id VARCHAR(128) NOT NULL,
  title VARCHAR(500) NOT NULL DEFAULT '',
  start_at DATETIME(3) NULL,
  end_at DATETIME(3) NULL,
  timezone VARCHAR(64) NULL,
  url VARCHAR(500) NULL,
  cover_url VARCHAR(500) NULL,
  is_free TINYINT(1) NULL,
  status VARCHAR(64) NULL,
  payload_json JSON NOT NULL,
  synced_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uniq_eb_user_event (user_id, external_id),
  INDEX idx_eb_user_start (user_id, start_at),
  CONSTRAINT fk_eb_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hightribe_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  external_id VARCHAR(128) NOT NULL,
  title VARCHAR(500) NOT NULL DEFAULT '',
  start_at DATETIME(3) NULL,
  end_at DATETIME(3) NULL,
  timezone VARCHAR(64) NULL,
  url VARCHAR(500) NULL,
  cover_url VARCHAR(500) NULL,
  location VARCHAR(500) NULL,
  status VARCHAR(64) NULL,
  payload_json JSON NOT NULL,
  synced_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uniq_ht_user_event (user_id, external_id),
  INDEX idx_ht_user_start (user_id, start_at),
  CONSTRAINT fk_ht_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
