CREATE TABLE IF NOT EXISTS channel_bookings (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  channel ENUM('hightribe', 'luma', 'eventbrite') NOT NULL,
  external_id VARCHAR(191) NOT NULL,
  event_external_id VARCHAR(128) NULL,
  event_title VARCHAR(500) NOT NULL DEFAULT '',
  guest_name VARCHAR(500) NOT NULL DEFAULT '',
  guest_email VARCHAR(320) NOT NULL,
  status VARCHAR(64) NULL,
  ticket_count INT NULL,
  registered_at DATETIME(3) NOT NULL,
  payload_json JSON NOT NULL,
  synced_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uniq_channel_booking (user_id, channel, external_id),
  INDEX idx_bookings_user_channel (user_id, channel, registered_at),
  CONSTRAINT fk_channel_bookings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
